// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOicEpnJ4Hj5PArztmFW2nqObgYRqeVfg',
    appId: '1:120120326894:web:d321e07baa9f05e44e51ff',
    messagingSenderId: '120120326894',
    projectId: 'my-mentor-project',
    authDomain: 'my-mentor-project.firebaseapp.com',
    storageBucket: 'my-mentor-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApc3X3WukhAd4ri-3BZN9VLx72rxtbqPg',
    appId: '1:120120326894:android:aa38d282542d84504e51ff',
    messagingSenderId: '120120326894',
    projectId: 'my-mentor-project',
    storageBucket: 'my-mentor-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdDV8YIgLgLntH4VKXkURsWju2eIi1vGg',
    appId: '1:120120326894:ios:fd6b0d5385bc76424e51ff',
    messagingSenderId: '120120326894',
    projectId: 'my-mentor-project',
    storageBucket: 'my-mentor-project.appspot.com',
    iosBundleId: 'com.example.mentorWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdDV8YIgLgLntH4VKXkURsWju2eIi1vGg',
    appId: '1:120120326894:ios:fd6b0d5385bc76424e51ff',
    messagingSenderId: '120120326894',
    projectId: 'my-mentor-project',
    storageBucket: 'my-mentor-project.appspot.com',
    iosBundleId: 'com.example.mentorWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOicEpnJ4Hj5PArztmFW2nqObgYRqeVfg',
    appId: '1:120120326894:web:0a3fa47ae168aae24e51ff',
    messagingSenderId: '120120326894',
    projectId: 'my-mentor-project',
    authDomain: 'my-mentor-project.firebaseapp.com',
    storageBucket: 'my-mentor-project.appspot.com',
  );
}
